services:
  multi-ocr-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi-ocr-service
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
